---
- name: "python{{python_version}} runtime&build dependencies"
  become: yes
  apt: name={{item}}
  with_items:
    - build-essential
    - tk-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline6-dev
    - libdb5.3-dev
    - libgdbm-dev
    - libsqlite3-dev
    - libssl-dev
    - libbz2-dev
    - libexpat1-dev
    - liblzma-dev
    - zlib1g-dev

- name: Check if python archive exists
  stat:
    path: /home/pi/Python-{{python_version}}.tar.xz
  register: python_archive

- name: Check if python3.6 is installed
  stat:
    path: /usr/local/bin/python3.6
  register: python_installed

- name: Check if pip3.6 is installed
  stat:
    path: /usr/local/bin/pip3.6
  register: pip_installed

- name: "Download python{{python_version}}"
  get_url:
    url="https://www.python.org/ftp/python/{{python_version}}/Python-{{python_version}}.tar.xz"
    dest="/home/pi/Python-{{python_version}}.tar.xz"
  when: python_archive.stat.exists == False

- name: "Unarchive python{{python_version}}"
  unarchive:
    src="/home/pi/Python-{{python_version}}.tar.xz"
    dest="/home/pi/"
    copy=no
    creates="/home/pi/Python-{{python_version}}"
   when: python_installed.stat.exists == False

- name: "configure python{{python_version}} build"
  command: ./configure
  args:
    chdir: "/home/pi/Python-{{python_version}}"
    creates: "/home/pi/Python-{{python_version}}/Makefile"
  when: python_installed.stat.exists == False

- name: "build python{{python_version}}"
  # not using make module to be able to use -j and creates option to fully skip step
  command: make -j4
  args:
    chdir: "/home/pi/Python-{{python_version}}"
    creates: "/home/pi/Python-{{python_version}}/python"
  when: python_installed.stat.exists == False

- name: "install python{{python_version}}"
  become: yes
  make:
    chdir: "/home/pi/Python-{{python_version}}"
    target: altinstall
  when: python_installed.stat.exists == False

- name: "Install pip modules"
  pip:
    name: "{{ item }}"
    executable: /usr/local/bin/pip3.6
  with_items:
    - pyserial
    - smbus2
    - idna
    - certifi
    - chardet
    - requests
    - RPi.bme280
    - configparser
  when: pip_installed.stat.exists == True