---
- name: Create a directory /etc/configuration directory
  file:
    path: /etc/configuration
    state: directory
    owner: pi
    group: pi
    mode: "0755"

- name: Copy bme280.py
  copy:
    src: "{{ item.src }}"
    dest: "/etc/configuration/"
    owner: pi
    group: pi
    mode: "0700"
    backup: yes
  with_items:
    - { src: "bme280.py"}
  when: temperature_sensor_model=="BME280"


- name: Copy sds python script
  copy:
    src: "{{ item.src }}"
    dest: "/etc/configuration/"
    owner: pi
    group: pi
    mode: "0700"
    backup: yes
  with_items:
    - { src: "sds011.py"}
    - { src: "smog_monitor.py"}
  when: particle_sensor_model=="SDS011" or particle_sensor_model=="SDS021"


- name: Copy pms python script
  copy:
    src: "{{ item.src }}"
    dest: "/etc/configuration/"
    owner: pi
    group: pi
    mode: "0700"
    backup: yes
  with_items:
    - { src: "running-pms.py"}
  when: particle_sensor_model=="PMS7003" or particle_sensor_model=="PMS5003"


- name: Copy ccs811 python script
  copy:
    src: "{{ item.src }}"
    dest: "/etc/configuration/"
    owner: pi
    group: pi
    mode: "0700"
    backup: yes
  with_items:
    - { src: "ccs811.py"}
    - { src: "CCS811_RPi.py"}
  when: co2_sensor_model=="CCS811"